#!/bin/bash

raw="${1}"

hrs=$(python -c "print( int($raw/3600.0))")
mins=$(python -c "print( int( ($raw - $hrs*3600)/60.0 ))")
secs=$(python -c "print( $raw - $hrs*3600 - $mins*60)")

echo "${hrs}h${mins}m${secs}s"
