#!/bin/bash

#--------------- Ajout des scripts au PATH ---------------------
export PATH="$(pwd)/Scripts/Automatisation-OpenFOAM/:${PATH}"
export PATH="$(pwd)/Scripts/Post-traitement/:${PATH}"

#-------------- Librairies Python -----------------------------------
export PYTHONPATH="$(pwd)/Scripts/Librairies/:${PYTHONPATH}"
export PYTHONPATH="$(pwd)/Scripts/Librairies/outils/:${PYTHONPATH}"
