#!/bin/bash

KNU_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo $KNU_PATH
#--------------- Ajout des scripts au PATH ---------------------
export PATH="${KNU_PATH}/Scripts/Automatisation-OpenFOAM/:${PATH}"
export PATH="${KNU_PATH}/Scripts/Post-traitement/:${PATH}"

#-------------- Librairies Python -----------------------------------
export PYTHONPATH="${KNU_PATH}/Scripts/Librairies/:${PYTHONPATH}"
export PYTHONPATH="${KNU_PATH}/Scripts/Librairies/outils/:${PYTHONPATH}"
