#!/bin/bash

echo "a1,b1,c1,a2,b2,c2,a3,b3,c3" > orientation.csv
grep "Orientation" log.overInterDyMFoam > temp.txt

sed "s/    Orientation: (//" -i temp.txt
sed "s/)//" -i temp.txt
sed "s/ /,/g" -i temp.txt

cat temp.txt >> orientation.csv
rm temp.txt

grep "^Time = " log.overInterDyMFoam |  grep -Eo '[+-]?[0-9]+([.][0-9]+)?' > times.csv

