#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cd oversetMesh

Allclean

cd ../backgroundMesh

Allclean

cd ..

#------------------------------------------------------------------------------
